database :
  user: "todouser"
  password: "todopass"
  dbname: "todolist_db"
  host: "localhost"
  port: 5433
  sslmode: "disable"

server:
  port: "8080"

#--JWT配置--
jwt:
  secret: "todo_jwt_secret"
  expirehours: 72

redis:
  addr: "localhost6379"
  password: ""
  db: 0